# Generated by Django 6.0.7 on 2026-07-09 17:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "ຜູ້ຈັດການ (ເບິ່ງໄດ້ໝົດ)"),
                            ("front_desk", "ໜ້າຮ້ານ (ເປີດບິນ)"),
                            ("technician", "ຊ່າງຊັກເກີບ"),
                        ],
                        default="technician",
                        max_length=20,
                        verbose_name="ໜ້າທີ່",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="ເບີໂທ"),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="ເປີເຊັນຈາກຄ່າບໍລິການຂອງວຽກທີ່ຊ່າງຄົນນີ້ເຮັດສຳເລັດ",
                        max_digits=5,
                        verbose_name="ອັດຕາຄອມມິດຊັນ (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ເຮັດວຽກຢູ່"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີສ້າງ"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ບັນຊີຜູ້ໃຊ້",
                    ),
                ),
            ],
            options={
                "verbose_name": "ພະນັກງານ",
                "verbose_name_plural": "ພະນັກງານ",
                "ordering": ["user__username"],
            },
        ),
    ]
