# Generated by Django 6.0.7 on 2026-07-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset_intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("before", "ກ່ອນບໍລິການ"), ("after", "ຫຼັງບໍລິການ")],
                        default="before",
                        max_length=10,
                        verbose_name="ໄລຍະ",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "ຮູບພາບ"), ("video", "ວິດີໂອ")],
                        default="image",
                        max_length=10,
                        verbose_name="ປະເພດໄຟລ໌",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="assets/%Y/%m/", verbose_name="ໄຟລ໌"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="ໝາຍເຫດ"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີອັບໂຫຼດ"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ໄຟລ໌ຫຼັກຖານ",
                "verbose_name_plural": "ໄຟລ໌ຫຼັກຖານ",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
