# Generated by Django 6.0.7 on 2026-08-17 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0009_alter_asset_status"),
        ("media_backup", "0002_mediafile_capture_angle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=300, verbose_name="ປາຍທາງ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "ກຳລັງແລ່ນ"),
                            ("success", "ສຳເລັດ"),
                            ("partial", "ສຳເລັດບາງສ່ວນ"),
                            ("failed", "ຜິດພາດ"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="ສະຖານະ",
                    ),
                ),
                (
                    "files_copied",
                    models.PositiveIntegerField(default=0, verbose_name="ໄຟລ໌ທີ່ສຳຮອງໄດ້"),
                ),
                (
                    "files_failed",
                    models.PositiveIntegerField(default=0, verbose_name="ໄຟລ໌ທີ່ຕົກ"),
                ),
                (
                    "bytes_copied",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="ຂະໜາດລວມ (bytes)"
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, verbose_name="ລາຍລະອຽດ/ຂໍ້ຜິດພາດ"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ເລີ່ມເມື່ອ"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ຈົບເມື່ອ"),
                ),
            ],
            options={
                "verbose_name": "ຮອບການສຳຮອງ",
                "verbose_name_plural": "ຮອບການສຳຮອງ",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="mediafile",
            name="backed_up_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ສຳຮອງເມື່ອ"),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="backup_ref",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="ບ່ອນເກັບສຳຮອງ"
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="checksum",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Checksum (sha256)"
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="size_bytes",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="ຂະໜາດ (bytes)"
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_media",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ພະນັກງານຜູ້ອັບໂຫຼດ",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(fields=["backed_up_at"], name="media_backed_up_idx"),
        ),
    ]
