# Generated by Django 6.0.7 on 2026-08-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_backup", "0003_backuprun_mediafile_backed_up_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="capture_angle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("front", "Front / toe box"),
                    ("heel", "Heel / rear"),
                    ("left", "Left side"),
                    ("right", "Right side"),
                    ("side", "Side profile"),
                    ("upper", "Upper / body"),
                    ("laces", "Laces"),
                    ("outsole", "Outsole"),
                    ("insole", "Insole"),
                    ("oxidation", "Sole yellowing (oxidation)"),
                    ("size_label", "Size label / SKU"),
                    ("inner", "Inner side / insole"),
                    ("box_accessories", "Box and accessories"),
                    ("defect", "Defect close-up"),
                ],
                max_length=30,
                verbose_name="ມຸມຮູບສຳລັບການປະເມີນ",
            ),
        ),
    ]
