# Generated by Django 6.0.7 on 2026-07-09 07:53

import digital_member.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        default=digital_member.models.generate_card_number,
                        max_length=20,
                        unique=True,
                        verbose_name="ເລກບັດ",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        default="basic",
                        max_length=10,
                        verbose_name="ລະດັບ",
                    ),
                ),
                (
                    "points_balance",
                    models.IntegerField(default=0, verbose_name="ຄະແນນສະສົມ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ໃຊ້ງານຢູ່")),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີອອກບັດ"),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_card",
                        to="crm.customer",
                        verbose_name="ລູກຄ້າ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ບັດສະມາຊິກ",
                "verbose_name_plural": "ບັດສະມາຊິກ",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="ຄະແນນ (+ ໄດ້ຮັບ / - ໃຊ້)")),
                ("reason", models.CharField(max_length=200, verbose_name="ເຫດຜົນ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີ"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="digital_member.membercard",
                        verbose_name="ບັດສະມາຊິກ",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="pos.order",
                        verbose_name="ອໍເດີທີ່ກ່ຽວຂ້ອງ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ລາຍການຄະແນນ",
                "verbose_name_plural": "ລາຍການຄະແນນ",
                "ordering": ["-created_at"],
            },
        ),
    ]
