# Generated by Django 6.0.7 on 2026-08-11 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercard",
            name="stamps_count",
            field=models.IntegerField(default=0, verbose_name="Stamp ສະສົມ"),
        ),
        migrations.AddField(
            model_name="membercard",
            name="stamps_redeemed",
            field=models.IntegerField(default=0, verbose_name="Stamp ທີ່ແລກສ່ວນຫຼຸດແລ້ວ"),
        ),
        migrations.CreateModel(
            name="StampTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ADD", "ເພີ່ມ Stamp"),
                            ("REDEEM", "ນຳໃຊ້ສ່ວນຫຼຸດ"),
                            ("RESET", "ເລີ່ມໃໝ່"),
                        ],
                        default="ADD",
                        max_length=10,
                        verbose_name="ການກະທຳ",
                    ),
                ),
                ("count", models.IntegerField(default=1, verbose_name="ຈຳນວນ Stamp")),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="ໝາຍເຫດ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີ"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stamp_transactions",
                        to="digital_member.membercard",
                        verbose_name="ບັດສະມາຊິກ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ລາຍການ Stamp",
                "verbose_name_plural": "ລາຍການ Stamp",
                "ordering": ["-created_at"],
            },
        ),
    ]
