# Generated by Django 6.0.7 on 2026-07-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="ຊື່ອຸປະກອນ")),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ລະຫັດ (SKU)"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="ອັນ", max_length=50, verbose_name="ຫົວໜ່ວຍ"),
                ),
                (
                    "quantity_on_hand",
                    models.IntegerField(default=0, verbose_name="ຈຳນວນຄົງເຫຼືອ"),
                ),
                (
                    "reorder_level",
                    models.IntegerField(default=0, verbose_name="ຈຸດສັ່ງຊື້ຄືນ"),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ຕົ້ນທຶນຕໍ່ໜ່ວຍ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ໃຊ້ງານຢູ່")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີສ້າງ"),
                ),
            ],
            options={
                "verbose_name": "ອຸປະກອນສາງ",
                "verbose_name_plural": "ອຸປະກອນສາງ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "ຮັບເຂົ້າ"),
                            ("out", "ເບີກອອກ"),
                            ("adjust", "ປັບຍອດ (+/-)"),
                        ],
                        max_length=10,
                        verbose_name="ປະເພດ",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="ຮັບເຂົ້າ/ເບີກອອກ ໃສ່ຈຳນວນບວກ; ປັບຍອດ ໃສ່ +/- ໄດ້",
                        verbose_name="ຈຳນວນ",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="ໝາຍເຫດ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີ"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="pos.order",
                        verbose_name="ອໍເດີທີ່ກ່ຽວຂ້ອງ",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.supply",
                        verbose_name="ອຸປະກອນ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ການເຄື່ອນໄຫວສະຕັອກ",
                "verbose_name_plural": "ການເຄື່ອນໄຫວສະຕັອກ",
                "ordering": ["-created_at"],
            },
        ),
    ]
