# Generated by Django 6.0.7 on 2026-08-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("pos", "0011_alter_expense_currency_alter_order_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="ໃຊ້ເທົ່າໃດຕໍ່ບໍລິການ 1 ຄັ້ງ — ຈະຄູນດ້ວຍຈຳນວນໃນບິນ",
                        verbose_name="ຈຳນວນທີ່ໃຊ້ຕໍ່ 1 ລາຍການ",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_usages",
                        to="pos.servicetype",
                        verbose_name="ບໍລິການ",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_usages",
                        to="inventory.supply",
                        verbose_name="ອຸປະກອນ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ອຸປະກອນທີ່ບໍລິການໃຊ້",
                "verbose_name_plural": "ອຸປະກອນທີ່ບໍລິການໃຊ້",
                "ordering": ["service_type__name", "supply__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service_type", "supply"),
                        name="unique_supply_per_service",
                    )
                ],
            },
        ),
    ]
