"""
Django base settings for core project.
ການຕັ້ງຄ່າພື້ນຖານ (ໃຊ້ຮ່ວມກັນລະຫວ່າງ dev ແລະ prod)

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# ໄຟລ໌ນີ້ຢູ່ core/core/settings/base.py ດັ່ງນັ້ນຕ້ອງ .parent 3 ຄັ້ງ
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ໂຫຼດ environment variables ຈາກໄຟລ໌ .env (ຢູ່ຂ້າງ manage.py)
# override=True — ໃຫ້ .env ຊະນະຄ່າເກົ່າທີ່ຄ້າງໃນ environment ສະເໝີ
# (ບໍ່ດັ່ງນັ້ນ autoreload ຂອງ runserver ຈະສືບທອດຄ່າເກົ່າ ແກ້ .env ແລ້ວບໍ່ມີຜົນ)
load_dotenv(BASE_DIR / ".env", override=True)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Local apps
    "ai_mart_grading",
    "asset_intake",
    "crm",
    "dashboard",
    "digital_member",
    "home",
    "inventory",
    "media_backup",
    "notifications",
    "pos",
    "reports",
    "resell_pricing_engine",
    "staff",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "staff.context_processors.staff_role",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "lo"

LANGUAGES = [
    ("lo", "ລາວ"),
    ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Asia/Vientiane"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Media files (uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ໜ້າ login ສຳລັບ @login_required (ໃຊ້ໜ້າ login ຂອງ admin ໄປກ່ອນ)
LOGIN_URL = "/admin/login/"

# ------------------------------------------------------------
# ການແຈ້ງເຕືອນລູກຄ້າ (Telegram) ແລະ ລິ້ງ Customer Portal
# ------------------------------------------------------------
# Base URL ຂອງເວັບ — ໃຊ້ສ້າງລິ້ງ portal/QR ໃນຂໍ້ຄວາມແຈ້ງເຕືອນ ແລະ ໃບຮັບເຄື່ອງ
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "http://127.0.0.1:8000")

# Token ຂອງ Telegram Bot (ສ້າງຜ່ານ @BotFather)
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
