"""
Django base settings for core project.
ການຕັ້ງຄ່າພື້ນຖານ (ໃຊ້ຮ່ວມກັນລະຫວ່າງ dev ແລະ prod)

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# ໄຟລ໌ນີ້ຢູ່ core/core/settings/base.py ດັ່ງນັ້ນຕ້ອງ .parent 3 ຄັ້ງ
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ໂຫຼດ environment variables ຈາກໄຟລ໌ .env (ຢູ່ຂ້າງ manage.py)
# override=True — ໃຫ້ .env ຊະນະຄ່າເກົ່າທີ່ຄ້າງໃນ environment ສະເໝີ
# (ບໍ່ດັ່ງນັ້ນ autoreload ຂອງ runserver ຈະສືບທອດຄ່າເກົ່າ ແກ້ .env ແລ້ວບໍ່ມີຜົນ)
load_dotenv(BASE_DIR / ".env", override=True)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Local apps
    "accounting",
    "ai_mart_grading",
    "asset_intake",
    "crm",
    "dashboard",
    "digital_member",
    "home",
    "inventory",
    "media_backup",
    "notifications",
    "pos",
    "reports",
    "resell_pricing_engine",
    "staff",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "staff.context_processors.staff_role",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "lo"

LANGUAGES = [
    ("lo", "ລາວ"),
    ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Asia/Vientiane"

USE_I18N = True

USE_TZ = True

FORMAT_MODULE_PATH = [
    "core.formats",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
# ໂຟນເດີ static ລະດັບ project (core/static/) — ບໍ່ຂຶ້ນກັບແອັບໃດແອັບໜຶ່ງ (logo, fonts, ລາຍເຊັນ...)
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------
# ການແຈ້ງເຕືອນລູກຄ້າ (Telegram) ແລະ ລິ້ງ Customer Portal
# ------------------------------------------------------------
# Base URL ຂອງເວັບ — ໃຊ້ສ້າງລິ້ງ portal/QR ໃນຂໍ້ຄວາມແຈ້ງເຕືອນ ແລະ ໃບຮັບເຄື່ອງ
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "http://127.0.0.1:8000")

# Token ຂອງ Telegram Bot (ສ້າງຜ່ານ @BotFather)
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")

# WhatsApp Business Cloud API (Meta) — ສົ່ງແຈ້ງເຕືອນຫາລູກຄ້າອັດຕະໂນມັດ
# ສະໝັກທີ່ developers.facebook.com > WhatsApp > API Setup
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")

# ------------------------------------------------------------
# POS — ໜ້າຄິດເງິນ
# ------------------------------------------------------------
# ສະກຸນເງິນຫຼັກ: ຍອດບິນ ແລະ ຍອດຄ້າງຄິດເປັນສະກຸນນີ້ສະເໝີ
POS_BASE_CURRENCY = os.getenv("POS_BASE_CURRENCY", "LAK")

# ອັດຕາແລກປ່ຽນເລີ່ມຕົ້ນ 1 ໜ່ວຍ → ສະກຸນຫຼັກ.
# ປະຫວ່າງໄວ້ = ບັງຄັບໃຫ້ພະນັກງານປ້ອນອັດຕາເອງທຸກຄັ້ງທີ່ຮັບເງິນສະກຸນອື່ນ
# (ອັດຕາຖືກລັອກເກັບໄວ້ໃນແຕ່ລະແຖວ Payment ຈຶ່ງທຽບບັນຊີຄືນໄດ້ສະເໝີ)
POS_FX_RATES = {}

# ------------------------------------------------------------
# ການອັບໂຫຼດຫຼັກຖານ (Scope 2.3 — Media Backup)
# ------------------------------------------------------------
# ໄຟລ໌ຫຼັກຖານເກັບລົງ disk ຂອງເຄື່ອງ ຈຶ່ງຕ້ອງມີເພດານ ບໍ່ດັ່ງນັ້ນວິດີໂອຄລິບດຽວ
# ກໍເຮັດໃຫ້ດິສເຕັມ ແລ້ວຮ້ານຮັບເຄື່ອງບໍ່ໄດ້ທັງລະບົບ
MAX_UPLOAD_IMAGE_MB = int(os.getenv("MAX_UPLOAD_IMAGE_MB", "12"))
MAX_UPLOAD_VIDEO_MB = int(os.getenv("MAX_UPLOAD_VIDEO_MB", "60"))

# ຈຳນວນໄຟລ໌ສູງສຸດຕໍ່ການອັບໂຫຼດ 1 ຄັ້ງ — ກັນການເລືອກທັງອະລະບ້ຳຮູບໃນມືຖື
MAX_UPLOAD_FILES_PER_REQUEST = int(os.getenv("MAX_UPLOAD_FILES_PER_REQUEST", "20"))

# ------------------------------------------------------------
# ຄະແນນສະສົມ (Scope 2.2 — Digital Member)
# ------------------------------------------------------------
# ໃຊ້ຈ່າຍຄົບເທົ່າໃດ (ສະກຸນຫຼັກ) ຈຶ່ງໄດ້ 1 ຄະແນນ. ຄິດຈາກຍອດບິນທີ່ຊຳລະຄົບ
# ຕັ້ງເປັນ 0 = ປິດການສະສົມຄະແນນ (ຮ້ານໃຊ້ແຕ່ລະບົບ Stamp)
LOYALTY_KIP_PER_POINT = int(os.getenv("LOYALTY_KIP_PER_POINT", "10000"))

STATIC_ROOT = BASE_DIR / "staticfiles"

# ໜ້າ login ຂອງຮ້ານ — ບໍ່ໃຊ້ໜ້າ admin ຂອງ Django ອີກ ເພາະໜ້ານັ້ນຮັບແຕ່ຜູ້ທີ່ is_staff
# ເຊິ່ງພະນັກງານທີ່ຮ້ານສ້າງເອງບໍ່ມີ ຈຶ່ງເຂົ້າລະບົບບໍ່ໄດ້
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard:index"
LOGOUT_REDIRECT_URL = "login"
