# Generated by Django 6.0.7 on 2026-07-09 07:53

import django.db.models.deletion
import django.utils.timezone
import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset_intake", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="ວັນທີ"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplies", "ອຸປະກອນ/ນ້ຳຢາ"),
                            ("rent", "ຄ່າເຊົ່າ"),
                            ("utility", "ຄ່ານ້ຳ/ໄຟ/ເນັດ"),
                            ("salary", "ເງິນເດືອນ"),
                            ("marketing", "ການຕະຫຼາດ"),
                            ("other", "ອື່ນໆ"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="ໝວດ",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="ລາຍລະອຽດ"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ຈຳນວນເງິນ"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("THB", "THB (ບາດ)"),
                            ("LAK", "LAK (ກີບ)"),
                            ("USD", "USD (ໂດລາ)"),
                        ],
                        default="THB",
                        max_length=3,
                        verbose_name="ສະກຸນເງິນ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ບັນທຶກເມື່ອ"),
                ),
            ],
            options={
                "verbose_name": "ລາຍຈ່າຍ",
                "verbose_name_plural": "ລາຍຈ່າຍ",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="ຊື່ບໍລິການ")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ລາຄາ"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ເປີດໃຫ້ບໍລິການ"),
                ),
            ],
            options={
                "verbose_name": "ປະເພດບໍລິການ",
                "verbose_name_plural": "ປະເພດບໍລິການ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=pos.models.generate_order_number,
                        max_length=20,
                        unique=True,
                        verbose_name="ເລກອໍເດີ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "ເປີດຢູ່"),
                            ("paid", "ຊຳລະແລ້ວ"),
                            ("cancelled", "ຍົກເລີກ"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="ສະຖານະ",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="ສ່ວນຫຼຸດ"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ໝາຍເຫດ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີສ້າງ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ອັບເດດລ່າສຸດ"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="crm.customer",
                        verbose_name="ລູກຄ້າ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ອໍເດີ",
                "verbose_name_plural": "ອໍເດີ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ຈຳນວນເງິນ"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("THB", "THB (ບາດ)"),
                            ("LAK", "LAK (ກີບ)"),
                            ("USD", "USD (ໂດລາ)"),
                        ],
                        default="THB",
                        max_length=3,
                        verbose_name="ສະກຸນເງິນ",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "ເງິນສົດ"),
                            ("transfer", "ໂອນເງິນ"),
                            ("qr", "ສະແກນ QR"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="ຊ່ອງທາງ",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີຊຳລະ"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="ໝາຍເຫດ"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="pos.order",
                        verbose_name="ອໍເດີ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ການຊຳລະເງິນ",
                "verbose_name_plural": "ການຊຳລະເງິນ",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ລາຍລະອຽດ"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="ຈຳນວນ"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ລາຄາຕໍ່ໜ່ວຍ"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.order",
                        verbose_name="ອໍເດີ",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="pos.servicetype",
                        verbose_name="ບໍລິການ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ລາຍການອໍເດີ",
                "verbose_name_plural": "ລາຍການອໍເດີ",
            },
        ),
    ]
