# Generated by Django 6.0.7 on 2026-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_order_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vat_rate",
            field=models.IntegerField(default=10, verbose_name="ອັດຕາ VAT (%)"),
        ),
    ]
