# Generated by Django 6.0.7 on 2026-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_servicetype_category_and_basic_clean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="category",
            field=models.CharField(
                choices=[
                    ("ai_assessment", "AI assessment"),
                    ("primary", "Primary service"),
                    ("add_on", "Add-on service"),
                    ("buyback", "Second-hand buy-back"),
                ],
                default="primary",
                max_length=20,
                verbose_name="ໝວດບໍລິການ",
            ),
        ),
    ]
