# Generated by Django 6.0.7 on 2026-08-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_seed_buyback_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("wash", "ຊັກ / ທຳຄວາມສະອາດ"),
                    ("repair", "ສ້ອມແປງ / ບູລະນະ"),
                    ("assess", "ປະເມີນສະພາບ"),
                    ("other", "ອື່ນໆ"),
                ],
                default="wash",
                help_text="ໃຊ້ແຍກແຖວວຽກໃນກະດານຕິດຕາມການເຮັດວຽກ",
                max_length=20,
                verbose_name="ປະເພດວຽກ",
            ),
        ),
    ]
