# Generated by Django 6.0.7 on 2026-08-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0008_servicetype_work_type_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("wash", "Washing & cleaning"),
                    ("repair", "Repair & restoration"),
                    ("assess", "Condition assessment"),
                    ("other", "Other work"),
                ],
                default="wash",
                help_text="ໃຊ້ແຍກແຖວວຽກໃນກະດານຕິດຕາມການເຮັດວຽກ",
                max_length=20,
                verbose_name="ປະເພດວຽກ",
            ),
        ),
    ]
