# Generated by Django 6.0.7 on 2026-08-12 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0009_servicetype_worktype_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ວັນທີຊຳລະຄົບ"),
        ),
        migrations.AddField(
            model_name="order",
            name="total_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ລັອກອັດຕະໂນມັດຕອນຊຳລະຄົບ — ແກ້ລາຄາພາຍຫຼັງຈະບໍ່ກະທົບໃບບິນເກົ່າ",
                max_digits=12,
                null=True,
                verbose_name="ຍອດລວມທີ່ລັອກໄວ້",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="ຈຳນວນເງິນ (ສະກຸນຫຼັກ)",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="change_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ເງິນທອນ"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="fx_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="ລັອກໄວ້ຕອນຈ່າຍ — ຄູນເປັນສະກຸນຫຼັກ (LAK)",
                max_digits=18,
                verbose_name="ອັດຕາແລກປ່ຽນ",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                help_text="ສ້າງຈາກຝັ່ງໜ້າຈໍ 1 ລະຫັດຕໍ່ 1 ການຈ່າຍ — ກົດຊ້ຳຈະບໍ່ບັນທຶກສອງແຖວ",
                null=True,
                unique=True,
                verbose_name="ລະຫັດກັນບັນທຶກຊ້ຳ",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[("payment", "ຮັບເງິນ"), ("refund", "ຄືນເງິນ")],
                default="payment",
                max_length=10,
                verbose_name="ປະເພດ",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ພະນັກງານຮັບເງິນ",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tendered_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ຈຳນວນທີ່ລູກຄ້າຍື່ນມາຈິງ (ໃຊ້ກັບເງິນສົດ)",
                max_digits=12,
                null=True,
                verbose_name="ເງິນທີ່ຮັບມາ",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="void_reason",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ເຫດຜົນການຍົກເລີກ"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ຍົກເລີກເມື່ອ"),
        ),
        migrations.AddField(
            model_name="payment",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ຜູ້ຍົກເລີກ",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "ເປີດຢູ່"),
                    ("partially_paid", "ຈ່າຍບາງສ່ວນ"),
                    ("paid", "ຊຳລະແລ້ວ"),
                    ("refunded", "ຄືນເງິນແລ້ວ"),
                    ("cancelled", "ຍົກເລີກ"),
                ],
                default="open",
                max_length=20,
                verbose_name="ສະຖານະ",
            ),
        ),
    ]
