# Generated by Django 6.0.7 on 2026-08-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0010_order_settled_at_order_total_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                choices=[
                    ("THB", "THB (Baht)"),
                    ("LAK", "LAK (Kip)"),
                    ("USD", "USD (Dollar)"),
                ],
                default="THB",
                max_length=3,
                verbose_name="ສະກຸນເງິນ",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open bill"),
                    ("partially_paid", "Partially paid"),
                    ("paid", "Paid in full"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=20,
                verbose_name="ສະຖານະ",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("THB", "THB (Baht)"),
                    ("LAK", "LAK (Kip)"),
                    ("USD", "USD (Dollar)"),
                ],
                default="THB",
                max_length=3,
                verbose_name="ສະກຸນເງິນ",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[("payment", "Payment in"), ("refund", "Refund")],
                default="payment",
                max_length=10,
                verbose_name="ປະເພດ",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("transfer", "Bank transfer"),
                    ("qr", "QR payment"),
                ],
                default="cash",
                max_length=20,
                verbose_name="ຊ່ອງທາງ",
            ),
        ),
    ]
