# Generated by Django 6.0.7 on 2026-07-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="ຊື່")),
                (
                    "phone",
                    models.CharField(max_length=30, unique=True, verbose_name="ເບີໂທ"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ອີເມວ"),
                ),
                (
                    "line_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LINE / WhatsApp"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Facebook"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="ທີ່ຢູ່")),
                ("note", models.TextField(blank=True, verbose_name="ໝາຍເຫດ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີສ້າງ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ອັບເດດລ່າສຸດ"),
                ),
            ],
            options={
                "verbose_name": "ລູກຄ້າ",
                "verbose_name_plural": "ລູກຄ້າ",
                "ordering": ["-created_at"],
            },
        ),
    ]
