# Generated by Django 6.0.7 on 2026-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ລູກຄ້າກົດ Start ໃສ່ bot ຂອງຮ້ານກ່ອນ ຈຶ່ງຈະໄດ້ chat id ມາຕື່ມບ່ອນນີ້",
                max_length=32,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
