# Generated by Django 6.0.7 on 2026-07-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset_intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ຫົວຂໍ້ກວດ")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("upper", "ໜ້າເກີບ (Upper)"),
                            ("sole", "ພື້ນເກີບ (Sole)"),
                            ("insole", "ພື້ນໃນ (Insole)"),
                            ("laces", "ສາຍເກີບ"),
                            ("box", "ກ່ອງ/ອຸປະກອນເສີມ"),
                            ("other", "ອື່ນໆ"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="ໝວດ",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(default=10, verbose_name="ຄະແນນເຕັມ"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ລຳດັບສະແດງ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ໃຊ້ງານຢູ່")),
            ],
            options={
                "verbose_name": "ຫົວຂໍ້ Checklist",
                "verbose_name_plural": "ຫົວຂໍ້ Checklist",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "ລໍຖ້າປະເມີນ"),
                            ("done", "ປະເມີນແລ້ວ"),
                            ("failed", "ຜິດພາດ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ສະຖານະ",
                    ),
                ),
                (
                    "overall_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A — ດີຫຼາຍ"),
                            ("B", "B — ດີ"),
                            ("C", "C — ພໍໃຊ້"),
                            ("D", "D — ຊຸດໂຊມ"),
                            ("F", "F — ເສຍຫາຍໜັກ"),
                        ],
                        max_length=1,
                        verbose_name="ເກຣດລວມ",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ຄະແນນລວມ",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="ສະຫຼູບຈາກ AI")),
                (
                    "ai_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AI Model"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ຄຳຕອບດິບຈາກ AI"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີປະເມີນ"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ການປະເມີນສະພາບ",
                "verbose_name_plural": "ການປະເມີນສະພາບ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="ຄະແນນ"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="ໝາຍເຫດ"),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ai_mart_grading.assessment",
                        verbose_name="ການປະເມີນ",
                    ),
                ),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="ai_mart_grading.checklistitem",
                        verbose_name="ຫົວຂໍ້ກວດ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ຄະແນນຫົວຂໍ້ກວດ",
                "verbose_name_plural": "ຄະແນນຫົວຂໍ້ກວດ",
            },
        ),
    ]
