# Generated by Django 6.0.7 on 2026-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mart_grading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="confidence_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ຄວາມໝັ້ນໃຈຂອງ AI (%)",
            ),
        ),
    ]
