# Generated by Django 6.0.7 on 2026-07-09 07:53

import asset_intake.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        default=asset_intake.models.generate_ticket_number,
                        max_length=20,
                        unique=True,
                        verbose_name="ເລກໃບຮັບເຄື່ອງ",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="ຍີ່ຫໍ້")),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=150, verbose_name="ລຸ້ນ"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="ສີ"),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=20, verbose_name="ເບີ"),
                ),
                (
                    "condition_note",
                    models.TextField(blank=True, verbose_name="ສະພາບຕອນຮັບເຄື່ອງ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "ຮັບເຂົ້າແລ້ວ"),
                            ("in_service", "ກຳລັງບໍລິການ"),
                            ("ready", "ພ້ອມສົ່ງຄືນ"),
                            ("returned", "ສົ່ງຄືນແລ້ວ"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="ສະຖານະ",
                    ),
                ),
                (
                    "intake_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີຮັບເຂົ້າ"),
                ),
                (
                    "pickup_date",
                    models.DateField(blank=True, null=True, verbose_name="ວັນນັດຮັບເຄື່ອງ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ອັບເດດລ່າສຸດ"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="crm.customer",
                        verbose_name="ລູກຄ້າ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ເຄື່ອງຮັບຝາກ",
                "verbose_name_plural": "ເຄື່ອງຮັບຝາກ",
                "ordering": ["-intake_date"],
            },
        ),
    ]
