# Generated by Django 6.0.7 on 2026-07-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "ຮັບເຂົ້າ (Intake)"),
                    ("cleaning", "ກຳລັງທຳຄວາມສະອາດ (Cleaning)"),
                    ("repairing", "ກຳລັງສ້ອມແປງ (Repairing)"),
                    ("ready", "ສຳເລັດ/ລໍຖ້າຮັບ (Ready for Pickup)"),
                    ("returned", "ສົ່ງມອບແລ້ວ (Completed)"),
                ],
                default="received",
                max_length=20,
                verbose_name="ສະຖານະ",
            ),
        ),
        migrations.CreateModel(
            name="AssetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="assets/%Y/%m/", verbose_name="ຮູບພາບ"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("before", "ກ່ອນຊັກ (Before)"),
                            ("after", "ຫຼັງຊັກ (After)"),
                        ],
                        default="before",
                        max_length=10,
                        verbose_name="ປະເພດຮູບ",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ອັບໂຫຼດເມື່ອ"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ຮູບພາບເກີບ",
                "verbose_name_plural": "ຮູບພາບເກີບ",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
