# Generated by Django 6.0.7 on 2026-07-17 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0003_asset_public_token_assigned_to_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(max_length=10, verbose_name="ໂຊນ")),
                ("cabinet", models.PositiveSmallIntegerField(verbose_name="ຕູ້")),
                ("position", models.PositiveSmallIntegerField(verbose_name="ຊ່ອງ")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ເປີດໃຊ້ງານ"),
                ),
            ],
            options={
                "verbose_name": "ບ່ອນເກັບເກີບ",
                "verbose_name_plural": "ບ່ອນເກັບເກີບ",
                "ordering": ["zone", "cabinet", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zone", "cabinet", "position"),
                        name="unique_storage_slot",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="storage_slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset",
                to="asset_intake.storageslot",
                verbose_name="ບ່ອນເກັບ",
            ),
        ),
    ]
