# Generated by Django 6.0.7 on 2026-08-11 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0005_storageslot_real_shelf_layout"),
        ("pos", "0007_servicetype_work_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageslot",
            name="cabinet",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="ຕູ້"),
        ),
        migrations.CreateModel(
            name="AssetService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="ຊື່ວຽກ"),
                ),
                (
                    "work_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ປະເພດວຽກ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "ລໍຖ້າ (Pending)"),
                            ("in_progress", "ກຳລັງເຮັດ (In progress)"),
                            ("done", "ແລ້ວ (Done)"),
                            ("skipped", "ຂ້າມ (Skipped)"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ສະຖານະ",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ເລີ່ມເມື່ອ"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ແລ້ວເມື່ອ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ສ້າງເມື່ອ"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ຊ່າງຮັບຜິດຊອບ",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_services",
                        to="pos.servicetype",
                        verbose_name="ບໍລິການ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ວຽກບໍລິການຕໍ່ຄູ່",
                "verbose_name_plural": "ວຽກບໍລິການຕໍ່ຄູ່",
                "ordering": ["asset", "work_type", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "service_type"), name="unique_asset_service"
                    )
                ],
            },
        ),
    ]
