# Generated by Django 6.0.7 on 2026-08-12 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0007_backfill_asset_services"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handed_over_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ພະນັກງານຜູ້ມອບ",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="returned_to",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="ຜູ້ມາຮັບເຄື່ອງ"
            ),
        ),
    ]
