# Generated by Django 6.0.7 on 2026-08-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0008_asset_returned_by_asset_returned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received (intake)"),
                    ("cleaning", "Cleaning in progress"),
                    ("repairing", "Repair in progress"),
                    ("ready", "Ready for pickup"),
                    ("returned", "Handed over"),
                ],
                default="received",
                max_length=20,
                verbose_name="ສະຖານະ",
            ),
        ),
    ]
