# Generated by Django 6.0.7 on 2026-08-17 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0009_alter_asset_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="ຊື່ຍີ່ຫໍ້"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ເປີດໃຫ້ເລືອກ"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="ເລກນ້ອຍຂຶ້ນກ່ອນ — ຍີ່ຫໍ້ທີ່ຮັບປະຈຳໃຫ້ໃສ່ເລກນ້ອຍ",
                        verbose_name="ລຳດັບ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີສ້າງ"),
                ),
            ],
            options={
                "verbose_name": "ຍີ່ຫໍ້ເກີບ",
                "verbose_name_plural": "ຍີ່ຫໍ້ເກີບ",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShoeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="ຊື່ລຸ້ນ")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ເປີດໃຫ້ເລືອກ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີສ້າງ"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shoe_models",
                        to="asset_intake.brand",
                        verbose_name="ຍີ່ຫໍ້",
                    ),
                ),
            ],
            options={
                "verbose_name": "ລຸ້ນເກີບ",
                "verbose_name_plural": "ລຸ້ນເກີບ",
                "ordering": ["brand__sort_order", "brand__name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "name"), name="unique_model_per_brand"
                    )
                ],
            },
        ),
    ]
