# Generated by Django 6.0.7 on 2026-07-13 07:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="ຊື່ໝວດ")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "ລາຍຮັບ"), ("OUT", "ລາຍຈ່າຍ")],
                        max_length=3,
                        verbose_name="ປະເພດ",
                    ),
                ),
                (
                    "color",
                    models.CharField(default="#22d3ee", max_length=7, verbose_name="ສີ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ໃຊ້ງານ")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ລຳດັບ"),
                ),
            ],
            options={
                "verbose_name": "ໝວດບັນຊີ",
                "verbose_name_plural": "ໝວດບັນຊີ",
                "ordering": ["transaction_type", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "transaction_type"),
                        name="unique_account_category",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="ໃຊ້ວັນທີ 1 ຂອງເດືອນ", verbose_name="ເດືອນ"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("THB", "THB (ບາດ)"),
                            ("LAK", "LAK (ກີບ)"),
                            ("USD", "USD (ໂດລາ)"),
                        ],
                        default="LAK",
                        max_length=3,
                        verbose_name="ສະກຸນເງິນ",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="ງົບປະມານ",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"transaction_type": "OUT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="accounting.accountcategory",
                        verbose_name="ໝວດ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ງົບປະມານ",
                "verbose_name_plural": "ງົບປະມານ",
                "ordering": ["-month", "category__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month", "category", "currency"),
                        name="unique_monthly_budget",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CashBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="ວັນທີ",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default=django.utils.timezone.localtime, verbose_name="ເວລາ"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="ລາຍການ"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "ລາຍຮັບ"), ("OUT", "ລາຍຈ່າຍ")],
                        db_index=True,
                        max_length=3,
                        verbose_name="ປະເພດ",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("THB", "THB (ບາດ)"),
                            ("LAK", "LAK (ກີບ)"),
                            ("USD", "USD (ໂດລາ)"),
                        ],
                        default="LAK",
                        max_length=3,
                        verbose_name="ສະກຸນເງິນ",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="ຈຳນວນເງິນ",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "ເງິນສົດ"),
                            ("transfer", "ໂອນເງິນ"),
                            ("qr", "ສະແກນ QR"),
                            ("other", "ອື່ນໆ"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="ຊ່ອງທາງ",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="ເລກອ້າງອີງ"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ໝາຍເຫດ")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to="accounting/receipts/%Y/%m/",
                        verbose_name="ຫຼັກຖານ/ໃບບິນ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "ຢືນຢັນແລ້ວ"),
                            ("draft", "ສະບັບຮ່າງ"),
                            ("void", "ຍົກເລີກ"),
                        ],
                        default="confirmed",
                        max_length=12,
                        verbose_name="ສະຖານະ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounting.accountcategory",
                        verbose_name="ໝວດ",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_entries_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ບັນທຶກໂດຍ",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_entries_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ແກ້ໄຂໂດຍ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ລາຍການບັນຊີ",
                "verbose_name_plural": "ລາຍການບັນຊີ",
                "ordering": ["-date", "-time", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["date", "currency", "transaction_type"],
                        name="accounting__date_569075_idx",
                    ),
                    models.Index(
                        fields=["status", "date"], name="accounting__status_7ba8af_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CashHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="ວັນທີ"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("THB", "THB (ບາດ)"),
                            ("LAK", "LAK (ກີບ)"),
                            ("USD", "USD (ໂດລາ)"),
                        ],
                        default="LAK",
                        max_length=3,
                        verbose_name="ສະກຸນເງິນ",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="ເງິນທອນຕົ້ນມື້",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="ຍອດຕາມລະບົບ",
                    ),
                ),
                (
                    "counted_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="ຍອດນັບໄດ້"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ໝາຍເຫດ")),
                ("received_by", models.CharField(max_length=120, verbose_name="ຜູ້ຮັບ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_handovers_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ຜູ້ສົ່ງມອບ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ການສົ່ງມອບເງິນ",
                "verbose_name_plural": "ການສົ່ງມອບເງິນ",
                "ordering": ["-date", "currency"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "currency"), name="unique_daily_cash_handover"
                    )
                ],
            },
        ),
    ]
