# Generated by Django 6.0.7 on 2026-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_seed_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="currency",
            field=models.CharField(
                choices=[
                    ("THB", "THB (Baht)"),
                    ("LAK", "LAK (Kip)"),
                    ("USD", "USD (Dollar)"),
                ],
                default="LAK",
                max_length=3,
                verbose_name="ສະກຸນເງິນ",
            ),
        ),
        migrations.AlterField(
            model_name="cashbook",
            name="currency",
            field=models.CharField(
                choices=[
                    ("THB", "THB (Baht)"),
                    ("LAK", "LAK (Kip)"),
                    ("USD", "USD (Dollar)"),
                ],
                default="LAK",
                max_length=3,
                verbose_name="ສະກຸນເງິນ",
            ),
        ),
        migrations.AlterField(
            model_name="cashhandover",
            name="currency",
            field=models.CharField(
                choices=[
                    ("THB", "THB (Baht)"),
                    ("LAK", "LAK (Kip)"),
                    ("USD", "USD (Dollar)"),
                ],
                default="LAK",
                max_length=3,
                verbose_name="ສະກຸນເງິນ",
            ),
        ),
    ]
