# Generated by Django 6.0.7 on 2026-08-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_budget_currency_alter_cashbook_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountcategory",
            name="is_internal_transfer",
            field=models.BooleanField(
                default=False,
                help_text="ໝວດນີ້ຈະບໍ່ຖືກນັບເປັນລາຍຮັບ ຫຼື ລາຍຈ່າຍ",
                verbose_name="ເປັນການຍ້າຍເງິນພາຍໃນ",
            ),
        ),
        migrations.AddField(
            model_name="cashbook",
            name="transfer_group",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="ລະຫັດຄູ່ຍ້າຍເງິນ",
            ),
        ),
    ]
