# Generated by Django 6.0.7 on 2026-07-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset_intake", "0003_asset_public_token_assigned_to_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
                        default="telegram",
                        max_length=20,
                        verbose_name="ຊ່ອງທາງ",
                    ),
                ),
                ("recipient", models.CharField(max_length=100, verbose_name="ຜູ້ຮັບ")),
                ("message", models.TextField(verbose_name="ຂໍ້ຄວາມ")),
                ("is_sent", models.BooleanField(default=False, verbose_name="ສົ່ງສຳເລັດ")),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="ຂໍ້ຜິດພາດ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີ"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ການແຈ້ງເຕືອນ",
                "verbose_name_plural": "ການແຈ້ງເຕືອນ",
                "ordering": ["-created_at"],
            },
        ),
    ]
