# Generated by Django 6.0.7 on 2026-08-13 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_intake", "0008_asset_returned_by_asset_returned_to"),
        ("crm", "0002_customer_telegram_chat_id"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="crm.customer",
                verbose_name="ລູກຄ້າ",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="asset_intake.asset",
                verbose_name="ເຄື່ອງຮັບຝາກ",
            ),
        ),
    ]
