# Generated by Django 6.0.7 on 2026-07-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_mart_grading", "0001_initial"),
        ("asset_intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ລາຄາຕ່ຳສຸດ"
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ລາຄາສູງສຸດ"
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ລາຄາແນະນຳ"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("THB", "THB (ບາດ)"),
                            ("LAK", "LAK (ກີບ)"),
                            ("USD", "USD (ໂດລາ)"),
                        ],
                        default="THB",
                        max_length=3,
                        verbose_name="ສະກຸນເງິນ",
                    ),
                ),
                ("reasoning", models.TextField(blank=True, verbose_name="ເຫດຜົນຈາກ AI")),
                (
                    "ai_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AI Model"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ຄຳຕອບດິບຈາກ AI"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີປະເມີນ"),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuations",
                        to="ai_mart_grading.assessment",
                        verbose_name="ການປະເມີນສະພາບ",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ການປະເມີນລາຄາ",
                "verbose_name_plural": "ການປະເມີນລາຄາ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("other", "ອື່ນໆ"),
                        ],
                        default="facebook",
                        max_length=20,
                        verbose_name="ແພລດຟອມ",
                    ),
                ),
                ("content", models.TextField(verbose_name="ເນື້ອຫາໂປຣໂມດ")),
                (
                    "ai_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AI Model"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ວັນທີສ້າງ"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_contents",
                        to="asset_intake.asset",
                        verbose_name="ເຄື່ອງຮັບຝາກ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ເນື້ອຫາໂປຣໂມດ",
                "verbose_name_plural": "ເນື້ອຫາໂປຣໂມດ",
                "ordering": ["-created_at"],
            },
        ),
    ]
