# Generated by Django 6.0.7 on 2026-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resell_pricing_engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricevaluation",
            name="currency",
            field=models.CharField(
                choices=[
                    ("THB", "THB (Baht)"),
                    ("LAK", "LAK (Kip)"),
                    ("USD", "USD (Dollar)"),
                ],
                default="THB",
                max_length=3,
                verbose_name="ສະກຸນເງິນ",
            ),
        ),
    ]
