# Generated by Django 6.0.7 on 2026-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resell_pricing_engine", "0002_alter_pricevaluation_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricevaluation",
            name="base_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="ລາຄາຕະຫຼາດພື້ນຖານ",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="condition_adjustment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="ປັບຕາມສະພາບ",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="confidence_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ຄວາມໝັ້ນໃຈຂອງ AI (%)",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="demand_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("High Demand", "ຄວາມຕ້ອງການສູງ"),
                    ("Normal Demand", "ຄວາມຕ້ອງການປົກກະຕິ"),
                    ("Low Demand", "ຄວາມຕ້ອງການຕ່ຳ"),
                ],
                max_length=20,
                verbose_name="ລະດັບຄວາມຕ້ອງການ",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="rarity_premium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="ບວກຄວາມຫາຍາກ",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="recommended_buy_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ລາຄາທີ່ຮ້ານຄວນສະເໜີຊື້ — ຕ່ຳກວ່າລາຄາຂາຍຕໍ່ສະເໝີ",
                max_digits=12,
                null=True,
                verbose_name="ລາຄາຮັບຊື້ທີ່ແນະນຳ",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="refurbishment_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="ຄ່າຟື້ນຟູ",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="risk_reserve",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="ສຳຮອງຄວາມສ່ຽງ",
            ),
        ),
        migrations.AddField(
            model_name="pricevaluation",
            name="target_margin_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ກຳໄລເປົ້າໝາຍ (%)",
            ),
        ),
        migrations.AlterField(
            model_name="pricevaluation",
            name="currency",
            field=models.CharField(
                choices=[
                    ("THB", "THB (Baht)"),
                    ("LAK", "LAK (Kip)"),
                    ("USD", "USD (Dollar)"),
                ],
                default="LAK",
                max_length=3,
                verbose_name="ສະກຸນເງິນ",
            ),
        ),
    ]
